"""Add Conversation and Message tables for AI Chatbot

Revision ID: 847b22276864
Revises: f43f1eaaa911
Create Date: 2026-01-30 23:42:53.270694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847b22276864'
down_revision: Union[str, Sequence[str], None] = 'f43f1eaaa911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
